simplesocial/groups/urls.py
from django.urls import path
from . import views

app_name='groups'

urlpatterns=[
    path('',views.ListGroups.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path('posts/in/(?P<slug>[-\w]+)/',views.SingleGroup.as_view(),name='single'),
    path('join/(?P<slug>[-\w]+)/',views.JoinGroup.as_view(),name='join'),
    path('leave/(?P<slug>[-\w]+)/',views.LeaveGroup.as_view(),name='leave'),
]

simplesocial/posts/urls.py
from django.urls import path

from . import views

app_name='posts'

urlpatterns=[
    path('',views.PostList.as_view(),name='all'),
    path('new/',views.CreatePost.as_view(),name='create'),
    path('by/(?P<username>[-\w]+)',views.UserPosts.as_view(),name='for_user'),
    path('by/(?P<username>[-\w]+)/(?P<pk>\d+)/',views.PostDetail.as_view(),name='single'),
    path('delete/(?P<pk>\d+)/',views.DeletePost.as_view(),name='delete')

]

simplesocial/simplesocial/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views   #this says that go to current directory and import views.py file
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.HomePage.as_view(),name='home'), #for class based views, we need to call as_view method
    path('accounts/',include('accounts.urls'),name='accounts'),
    path('accounts/',include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
    path('posts/',include('posts.urls',namespace='posts')),
    path('groups/',include('groups.urls',namespace='groups')),
]

simplesocial/groups/models.py
from django.db import models
from django.utils.text import slugify
import misaka 
from django.urls import reverse
from django.contrib.auth import get_user_model

User=get_user_model() #we get current user from here, who is playing around with the website right now
from django import template
register = template.Library() #this is how we can use custom template tags in the future, later on we will have, "in group members check template tag" while dealing with group html files

class Group(models.Model):
    name=models.CharField(max_length=255,unique=True) #name of the group, here "unique=true" means groups will have unique names
    slug=models.SlugField(allow_unicode=True,unique=True)#group names should not overlap after slugify
    description=models.TextField(blank=True,default='')#description of the group
    description_html=models.TextField(editable=False,default='',blank=True)
    members=models.ManyToManyField(User,through='GroupMember')

    def __str__(self):
        return self.name
    
    def save(self,*args,**kwargs):
        self.slug = slugify(self.name) #whatever the group name is(having spaces while filling out the form), it essentially just replace and lowercase things 
        self.description_html=misaka.html(self.description)
        super().save(*args,**kwargs)

    def get_absolute_url(self):
        return reverse('groups:single',kwargs={'slug':self.slug})
    
    class Meta:
        ordering=['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='memberships',on_delete=models.CASCADE,) #groupmember is related to the member class through this foreign key which we called memberships, which makes sense because a group member will have a membership to the group
    user=models.ForeignKey(User,related_name='user_groups',on_delete=models.CASCADE,) #we have user who will belong to some groups or who will be the member of some groups, we want to link this groupmember class to both the user and the groups that this user could belong to

    def __str__(self):
        return self.user.username
    
    class Meta:
        unique_together=('group','user')

# Create your models here.

simplesocial/groups/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.contrib import messages
from django.urls import reverse
from django.views import generic
from groups.models import Group,GroupMember
from . import models
from django.shortcuts import get_object_or_404
class CreateGroup(LoginRequiredMixin,generic.CreateView): #if someone is logged into the group and wants to create a group, this will be the view for that
    fields=('name','description') #this user can edit only name and description of the group, which are directly connected to the Group class in models.py file
    model=Group #connect it to group model
    
class SingleGroup(generic.DetailView):#details of the group,like the posts inside that group
    model= Group

class ListGroups(generic.ListView): #when someone goes to listgroups page, the user should see list of all groups
    model = Group

class JoinGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})
    def get(self,request,*args,**kwargs):
        group=get_object_or_404(Group,slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)
        except IntegrityError:
            messages.warning(self.request,'warning already a member!!')
        else:
            messages.success(self.request,'You are now a member!!')
        return super().get(request,*args,**kwargs)


class LeaveGroup(LoginRequiredMixin,generic.RedirectView):
    def get_redirect_url(self,*args,**kwargs):
        return reverse('groups:single',kwargs={'slug':self.kwargs.get('slug')})

    def get(self,request,*args,**kwargs):

        try:
            membership=models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get('slug')
            ).get()
        except models.GroupMember.DoesNotExist:
            messages.warning(self.request,'Sorry you are not in this group!!')
        else:
            membership.delete()
            messages.success(self.request,'you have left the group!!')
        return super().get(request,*args,**kwargs)


 

simplesocial/groups/templates/groups/group_base.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <div class="row">
        {% block pregroup %}{% endblock %}
        {% block group_content %}{% endblock %}
        {% block postgroup %}{% endblock %}
    </div>
</div>


{% endblock %}

simplesocial/groups/templates/groups/group_detail.html
{% extends "groups/group_base.html" %}
{% block pregroup %}

<h1>{{group.name}}</h1> 
<!--   with the class based views, a context dictionary is passed that holds everything that the model has -->

<!-- The most important thing about class based views:::::
    This "group" dictionary comes from the Group class of models.py file. The name of the dictionary is "g"roup(lowercase) because
    the name of the class is "G"roup(uppercase). In short, "group" is the lowercase singluar version of the actual model-->
<h2>Member Count: {{group.members.count}}</h2>
<div class="content">
    {% if user in group.members.all %}
        <a href="{% url 'groups:leave' slug=group.slug %}"
        class='btn btn-lg btn-fill btn-warning'><span
        class='glyphicon glyphicon-remove-circle'></span>Leave</a>
    {% else %}
    <a href="{% url 'groups:leave' slug=group.slug %}"
       class='btn btn-lg btn-fill btn-warning'><span
       class='glyphicon glyphicon-remove-circle'></span>Leave</a>
    {% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
    {% if group.posts.count == 0 %} <!-- if the group doesn't have any post -->
        <h2>No posts in this group yet!</h2>
    {% else %}
        {% for posts in group.posts.all %}
          {% include "posts/_post.html" %}
          <!-- include is a way to say extend but here we are inserting an html file in the middle of an html file. Instead of extending and using blocks, use include statement to inject
               an html file. Since it is very tough with the posts, a lot of html calls, lot of template calls, lot of template tags.. They cannot be written here, so write all of them 
               in _post.html file and inject here -->
        {% endfor %}
    {% endif %}
{% endblock %}


</div>

simplesocial/groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}

{% block group_content %}
<h4>Create a new group!</h4>

<form action="{% url 'groups:create' %}" method="post" id='groupForm'>
    {% csrf_token %}
    {% bootstrap_form form %}

    <input type="submit" class='btn btn-primary btn-large' value="Create">
</form>
{% endblock %}

simplesocial/groups/templates/groups/group_list.html
{% extends "groups/group_base.html" %}

{% block pregroup %}
<div class="col-md-4">
    <div class="content">
        {% if user.is_authenticated %}
        <h2>Welcome Back!
            <a href="{% url 'posts:for_user' username=user.username %}">
                @{{user.username}}
            </a>
        </h2>
        {% endif %}
        <h2>Groups</h2>
        <p>Welcome to the groups page!</p>
    </div>
    {% if user.is_authenticated %}
    <a href="{% url 'groups:create' %}" class='btn btn-md btn-fill btn-warning'>
        <span class='glyphicon glyphicon-plus-sign'> Create New Group!</span>
    </a>
    {% endif %}
</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8">
    <div class="list-group">
        {% for group in objects_list %} <!-- all this for is doing is displaying group name, no. of group members, no. of group posts.. then if the user clicks on the group name  -->
        <a class='list-group-item' href="{% url 'groups:single' slug=group.slug %}"> <!-- it will take it to actual group page -->
            <h3 class='title list-group-item-heading'>{{group.name}}</h3>
            <div class="list-group-item-text container-fluid">
                {{group.description_html|safe}}
                <div class="row">
                    <div class="col-md-4">
                        <span class='badge'>{{group.members.count}}</span>
                        member{{group.members.count|pluralize}}
                    </div>
                    <div class="col-md-4">
                        <span class='badge'>{{group.posts.count}}</span>
                        post{{group.posts.count|pluralize}}
                    </div>
                </div>
            </div>
        </a>
        {% endfor %}
    </div>
</div>

{% endblock %}